package com.interpreter.ameya.lexer;

public enum TokenType {
    // Single Character Tokens
    SEMI_COL, CURLY_LEFT, CURLY_RIGHT, LEFT_PAREN, RIGHT_PAREN, COMMA,
    DOT, PLUS, MINUS, STAR, SLASH, INTEGER_DIV, MOD,

    // Double & Single Tokens
    BANG, BANG_EQUAL,
    EQUAL, EQUAL_EQUAL,
    GREATER, GREATER_EQUAL,
    LESS, LESS_EQUAL,
    PLUS_EQUAL, MINUS_EQUAL, STAR_EQUAL,
    SLASH_EQUAL, MOD_EQUAL, INTEGER_DIV_EQUAL,

    // Literals
    INDENTIFIER, STRING, DOUBLE, INT,

    // Bitwise Operator
    BITWISE_AND, BITWISE_OR, BITWISE_XOR, BITWISE_NOT,
    RIGHT_SHIFT, LEFT_SHIFT, RIGHT_SHIFT_EQUAL,
    LEFT_SHIFT_EQUAL, AND_EQUAL, OR_EQUAL, XOR_EQUAL,

    // Keywords
    AND, OR, XOR, FOR, WHILE, IF, ELSE, ELIF,
    CONTINUE, BREAK, PRINT, FUNC, RETURN,
    CLASS, THIS, SUPER, VAR, CONST, NIL, TRUE, FALSE,

    EOF
}